from enum import Enum

class Code(Enum):
	CAP = 'CAP'
	INVITE = 'INVITE'
	JOIN = 'JOIN'
	NICK = 'NICK'
	NOTICE = 'NOTICE'
	PASS = 'PASS'
	PING = 'PING'
	PONG = 'PONG'
	PRIVMSG = 'PRIVMSG'
	USER = 'USER'
	WHOIS = 'WHOIS'
	RPL_WELCOME = 1
	RPL_WHOISREGNICK = 307
	RPL_ENDOFWHOIS = 318
	RPL_WHOISACCOUNT = 330
	ERR_NICKNAMEINUSE = 433
	ERR_ALREADYREGISTRED = 462
